site_name: Python Client to access data of Devices on Drift Platform
docs_dir: .
nav:
  - Home: README.md
  - API Reference:
      - DriftClient: docs/api/drift_client.md
      - Package: docs/api/package.md


repo_name: reduct-storage/reduct-py
repo_url: https://github.com/panda-official/DriftPythonClient
edit_uri: edit/main/docs


# Configuration
theme:
  name: material
  language: en

  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - plantuml_markdown:
      format: svg

plugins:
  - same-dir
  - mkdocstrings:
      default_handler: python
      enable_inventory: false
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_bases: false
            show_source: false
          selection:
            docstring_style: google
  - autorefs

